services:
  phppgadmin:
    container_name: phppgadmin
    restart: unless-stopped
    image: ngosang/phppgadmin:7.14.6-mod-1
    volumes:
    - ./config.inc.php:/var/www/app/conf/config.inc.php:ro
    ports:
    - 8080:80

  frontend:
    # Based on szurubooru/client:2.5
    build: ./client 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Timezone
      TZ: 'Europe/Moscow'
      # Backend "hostname:port"
      BACKEND_HOST: 'host.docker.internal:6667'
      BASE_URL: 
    volumes:
      - ./data:/data:ro
    ports:
      - 80:80

  postgresql:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: axumbooru
      POSTGRES_PASSWORD: axumbooru
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
